image: node:16

stages:
  - test

lint:
  stage: test
  script:
    - npm install
    - npm run compile
    - npm run solhint
    - npm run eslint
    - npm run prettier

test:
  stage: test
  artifacts:
    paths:
      - coverage/
  script:
    - npm install
    - npx hardhat compile
    - npx hardhat typechain
    - npx hardhat coverage
    - npx hardhat run scripts/deploy-bridge.ts
    - npx hardhat run scripts/deploy-system.ts

pages:
  stage: test
  needs:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - main
