image: node:16

stages:
  - test

test:lint:sol:
  stage: test
  script:
    - npm install
    - npm run solhint

test:lint:ts:
  stage: test
  script:
    - npm install
    - npm run compile
    - npm run eslint
    - npm run prettier

test:build:
  stage: test
  script:
    - npm install
    - npx hardhat compile
    - npx hardhat typechain

test:deploy:
  stage: test
  services:
    - name: trufflesuite/ganache-cli:latest
      alias: ganache
  script:
    - npm install
    - npx hardhat --network ganache run scripts/deploy-bridge.ts
    - npx hardhat --network ganache run scripts/deploy-system.ts

test:unit:
  stage: test
  script:
    - npm install
    - npm run compile
    - npx hardhat test
