image: node:16

stages:
  - test

lint:solhint:
  stage: test
  script:
    - npm install
    - npm run solhint

lint:eslint:
  stage: test
  script:
    - npm install
    - npm run compile
    - npm run eslint

lint:prettier:
  stage: test
  script:
    - npm install
    - npm run prettier

test:build:
  stage: test
  script:
    - npm install
    - npx hardhat compile
    - npx hardhat typechain

test:deploy:
  stage: test
  services:
    - name: trufflesuite/ganache-cli:latest
      alias: ganache
  script:
    - npm install
    - npx hardhat --network ganache run scripts/deploy-bridge.ts
    - npx hardhat --network ganache run scripts/deploy-system.ts

test:unit:
  stage: test
  script:
    - npm install
    - npm run compile
    - npx hardhat coverage
  artifacts:
    paths:
      - coverage/

pages:
  stage: test
  dependencies:
    - test:unit
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
